image: tmaier/docker-compose:latest
services:
  - docker:dind

stages:
  - build
  - lint
  - test

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
  except:
    - master

lint:
  stage: lint
  script:
    - docker-compose -f docker-compose.yml run -e ENV=LINT permissions_component
  except:
    - master

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml run -e ENV=TEST permissions_component
  except:
    - master
