version: 2
jobs:
  install:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Test
          command: npm run test
  lint:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: Lint
          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install